### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by microbit-mark** [KitronikLtd/pxt-kitronik-klef-piano#1]
pxt.json references v0.0.1m https://github.com/KitronikLtd/pxt-kitronik-klef-piano/blob/cfdb8398ce143f04ec16203dae33e7d5d813de76/pxt.json#L3 but there is no tagged release with that name https://github.com/KitronikLtd/pxt-kitronik-klef-piano/releases hence help is not rendered https://github.com/microsoft/pxt-microbit/issues/1858#issuecomment-594636395

@AlasdairAtKitronik

**Comment by AlasdairAtKitronik** [comment]
Release created.
